language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
  - '4'
before_script:
  - npm prune
script:
  - git --version
  - git tag --sort version:refname || true
  - git tag
  - npm test
after_success:
  - DEBUG=github-post-release npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
