language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
before_script:
  - npm prune
after_success:
  - DEBUG=github-post-release npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
